from __future__ import annotations

from labpilot.tokens import CHARS_PER_TOKEN

CHUNK_SIZE = 500
CHUNK_OVERLAP = 50
MAX_CHUNK_TOKENS = 510
MIN_CHUNK_TOKENS = 30

MAX_CHARS = MAX_CHUNK_TOKENS * CHARS_PER_TOKEN
MIN_CHARS = MIN_CHUNK_TOKENS * CHARS_PER_TOKEN

MIN_PDF_CHARS_PER_PAGE = 100
MIN_PDF_WORDS_WITH_VOWELS = 0.40

MAX_DOCX_XML_BYTES = 10_000_000

MAX_MEAN_LINE_CHARS = MAX_CHARS
