from __future__ import annotations

DEFAULT_TIMEOUT: tuple[float, float] = (10.0, 180.0)
DEFAULT_MAX_TOKENS = 1024
DEFAULT_TEMPERATURE = 0.0
ERROR_BODY_CHARS = 300
DEFAULT_MAX_RETRIES_PER_TIER = 1
DEFAULT_BASE_DELAY = 1.0
DEFAULT_MAX_DELAY = 30.0
DEFAULT_TOTAL_BUDGET = 300.0
RATE_LIMIT_WINDOW = 60.0
HTTP_TOO_MANY_REQUESTS = 429
CHARS_PER_TOKEN = 3
SAFETY_MARGIN_RATIO = 0.10
